name: Auto Merge Dev to Main

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch: 

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout dev branch
        run: git checkout dev

      - name: Merge dev into main
        run: |
          git checkout main
          git merge dev --no-ff --no-edit

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
